fabric:
  gatewayplus:
    conn:
      single-peer-info:
        tls-cert-path: /mnt/F/fabric-samples/fabric-samples-2.4.8/fabric-samples/test-network/organizations/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/tls/ca.crt
        endpoint: localhost:7051
        authority: peer0.org1.example.com
    pool:
      use-pool: true